# Documentation at https://github.com/cosmtrek/air/blob/master/air_example.toml
root = "."

[build]
args_bin = ["--log-level", "debug"]
bin = "./main"
cmd = "go build -o ./main ./cmd/app/main.go"
delay = 500
exclude_dir = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go"]
include_file = [] # broken on air v1.51.0
kill_delay = "2s"
log = ""
poll = false
poll_interval = 500
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 0
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
