name: Docker Hub description
on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3.4.2
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: qmcgaw/go-template-docker
          short-description: SHORT_DESCRIPTION
          readme-filepath: README.md
