name: latest
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/latest.yml
      - cmd/**
      - internal/**
      - pkg/**
      - .dockerignore
      - .golangci.yml
      - Dockerfile
      - go.mod
      - go.sum

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build base image
        run: docker build --target base -t base .
        env:
          DOCKER_BUILDKIT: "1"
      - name: Run tests in container
        run: |
          docker run --rm -e CGO_ENABLED=1 base \
          go test \
          -race \
          -coverpkg=./... \
          -coverprofile=coverage.txt \
          -covermode=atomic \
          ./...
      - name: Linting
        run: docker build --target lint .
        env:
          DOCKER_BUILDKIT: "1"
      - name: Go mod tidy check
        run: docker build --target tidy .
        env:
          DOCKER_BUILDKIT: "1"
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=commit::$(git rev-parse --short HEAD)
          echo ::set-output name=build_date::$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo ::set-output name=version::latest
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v6,linux/arm/v7,linux/s390x,linux/ppc64le,linux/riscv64
          build-args: |
            BUILD_DATE=${{ steps.vars.outputs.build_date }}
            COMMIT=${{ steps.vars.outputs.commit }}
            VERSION=${{ steps.vars.outputs.version }}
          tags: qmcgaw/reponame_docker:${{ steps.vars.outputs.version }}
          push: true
      - name: Microbadger hook
        run: curl -X POST https://hooks.microbadger.com/images/qmcgaw/REPONAME_DOCKER/WEBHOOK_LINK
        continue-on-error: true
