name: Pull request
on:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/pr.yml
      - cmd/**
      - internal/**
      - .dockerignore
      - .golangci.yml
      - Dockerfile
      - go.mod
      - go.sum

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          DOCKER_BUILDKIT: "1"
        run: docker build --target test .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          DOCKER_BUILDKIT: "1"
        run: docker build --target lint .

  docker:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Docker build
        run: |
          docker buildx build \
            --platform=linux/amd64 \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg COMMIT=`git rev-parse --short HEAD` \
            --build-arg VERSION="branch-${GITHUB_REF##*/}" \
            -t qmcgaw/REPONAME_DOCKER:branch-${GITHUB_REF##*/} \
            .
