name: Pull request
on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/pr.yml
      - cmd/**
      - internal/**
      - .dockerignore
      - .golangci.yml
      - Dockerfile
      - go.mod
      - go.sum

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build base image
        run: docker build --target base -t base .
        env:
          DOCKER_BUILDKIT: "1"
      - name: Run tests in container
        run: |
          docker run --rm -e CGO_ENABLED=1 base \
          go test \
          -race \
          -coverpkg=./... \
          -coverprofile=coverage.txt \
          -covermode=atomic \
          ./...
      - name: Linting
        run: docker build --target lint .
        env:
          DOCKER_BUILDKIT: "1"
      - name: Go mod tidy check
        run: docker build --target tidy .
        env:
          DOCKER_BUILDKIT: "1"
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          build-args: |
            BUILD_DATE={{ date -u +%Y-%m-%dT%H:%M:%SZ }}
            COMMIT={{ git rev-parse --short HEAD }}
            VERSION=branch-${{ github.head_ref }}
          tags: qmcgaw/reponame_docker:branch-${{ github.head_ref }}
          push: false
