name: release
on:
  release:
    types: [published]
    paths:
      - .github/workflows/release.yml
      - cmd/**
      - internal/**
      - .dockerignore
      - .golangci.yml
      - Dockerfile
      - go.mod
      - go.sum

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          DOCKER_BUILDKIT: "1"
        run: docker build --target base -t base .
      - name: Run tests in container
        run: |
          docker run --rm -e CGO_ENABLED=1 base \
          go test \
          -race \
          -coverpkg=./... \
          -coverprofile=coverage.txt \
          -covermode=atomic \
          ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          DOCKER_BUILDKIT: "1"
        run: docker build --target lint .

  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          DOCKER_BUILDKIT: "1"
        run: docker build --target tidy .

  docker:
    runs-on: ubuntu-latest
    needs: [test, lint, tidy]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v6,linux/arm/v7,linux/s390x,linux/ppc64le
          build-args: |
            BUILD_DATE={{ date -u +%Y-%m-%dT%H:%M:%SZ }}
            COMMIT={{ git rev-parse --short HEAD }}
            VERSION=${GITHUB_REF##*/}
          tags: qmcgaw/reponame_docker:${GITHUB_REF##*/}
          push: true
